### PR TITLE
added instructions for packaging with Electron

### PR DESCRIPTION
**Pull request by barischj**
relates to #111 and #52 

I recommend reading the instructions as [rendered markdown](https://github.com/barischj/threepenny-gui/blob/feature/electron/doc/electron.md) rather than in the "Files changed" menu

- instructions included as `docs/electron.md`
  - justification for Electron
  - how to run with Electron
  - packaging with electron-packager
-  included reference `package.json` and `electron.js` files

### CODE REVIEW

**Comment by HeinrichApfelmus** [comment]
This looks very useful, thank you!

However, there is one small problem: If I understand this correctly, when using the Electron packager to generate an application package, the package will still depend on a precise location of the executable via the `relBin` variable in `electron.js`.

Could you change your pull request so that the executable is automatically built and copied to the right location when building a package?

I have done something like this in my HyperHaskell project, you can probably just adapt the [`Makefile`](https://github.com/HeinrichApfelmus/hyper-haskell/blob/master/Makefile) and provide a new one in `doc/electron/Makefile`.

**Comment by barischj** [comment]
Yep, I'll have a look at that in the next few days

**Comment by barischj** [comment]
Just an update that I've been a bit busy but have some free time to tackle this shortly

**Comment by HeinrichApfelmus** [comment]
I know the feeling. 😉 I'd be happy to include this in the upcoming 0.8 release if you can find the time, but no worries if not, there's always a next release.

**Comment by barischj** [comment]
`relBin` is a relative path from `electron.js` to the Haskell application binary. I've added instructions for Stack users on how to build the Haskell application binary application to an explicit location, such that `relBin` can be set to something simple like `./build/your-app-exe`.

The previous electron-packager instructions would copy the entire directory to the app (including the Haskell application binary). Added instructions on ignoring things like `app/`, `src/`, and `.stack-work/`.

Also added a link to a minimal working example [here](https://github.com/barischj/threepenny-gui-electron-example).

**Comment by HeinrichApfelmus** [comment]
Thanks a lot for this! I will highlight this in the README.

**Pull request merged**
