### PR TITLE
Updates for GHC-8.8.1

### PR DESCRIPTION
**Pull request by sjakobi**
This is still blocked on `snap-server`, ~~which itself is blocked on https://github.com/snapframework/snap-core/issues/288.~~

### CODE REVIEW

**Comment by sjakobi** [comment]
Now blocked on https://github.com/snapframework/snap-server/pull/127.

**Comment by sjakobi** [comment]
Builds with GHC 7.6 and 7.8 are broken due to https://github.com/jaspervdj/websockets/issues/200.

@HeinrichApfelmus Would you mind if I merge and make a release anyway?

I guess I could add some constraints on `websockets` conditional on the GHC version, but that seems like too much hassle for an issue that will hopefully be fixed with the next `websockets` version…

**Comment by sjakobi** [comment]
Alternatively we could simply remove support for GHC < 7.10 – I think it could be time for that.

**Comment by HeinrichApfelmus** [comment]
> Alternatively we could simply remove support for GHC < 7.10 – I think it could be time for that.

Yes, that is fine with me. If I understand correctly, GHC 7.8 was released in 2014, I think that is past the time window where it is worth spending effort on.

And thanks again for your support, Simon! Happy Holidays and a Happy New Year to you and your close ones! 🎉

**Comment by sjakobi** [comment]
Frohe Weihnachten, Heinrich! :)

**Pull request merged**
