### PR TITLE
Fix refX, refY spelling

### PR DESCRIPTION
**Pull request by ggreif**
It appears to be case sensitive in FireFox.

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/refX

To be clarified:
- [ ] change spelling of Haskell r/w attribute too? (means version bump)
- [x] introduce Haskell aliases `refX` and `refY`? (means **minor version** bump, preferred)
- [x] deprecate old Haskell `refx` and `refy` bindings?

### CODE REVIEW

**Comment by sjakobi** [comment]
Did you check that the new spelling is compatible with other browsers?

**Comment by sjakobi** [comment]
LGTM!

**Comment by HeinrichApfelmus** [comment]
Nice! Looks just like a simple spelling mistake, indeed.

@sjakobi Feel free to merge this change. I think the [deprecation allows a minor version bump][1], but it might not be accepted to Hackage if I understand correctly. It might require a version bump to ≥ 0.9.0.0 .

  [1]: https://github.com/haskell/pvp/issues/12

**Comment by sjakobi** [comment]
> I think the [deprecation allows a minor version bump](https://github.com/haskell/pvp/issues/12), but it might not be accepted to Hackage if I understand correctly.

In my understanding, it's packages that use `-Werror` that are rejected by Hackage. A minor version bump should be fine for this release.

**Pull request merged**
